[package]
name = "cosmic-macros"
version = "0.3.0"
edition = "2021"

authors = ["Scott Williams <scott@mightydevco.com>"]
description = "macros for thecosmicinitiative.io"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]

cosmic-space = { path= "../cosmic-space", default-features=false,version = "0.3.0"}
lazy_static = "1.4.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
strum = "0.21.0"
strum_macros = "0.21.1"
regex = "1.5.4"
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
serde = "1.0.79"
chrono = { version="0.4.19", features=["serde"] }
uuid = { version="1.1.2", features=["v4"] }