[package]
name = "cosmic-artifact-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-universe={ path= "../../cosmic/cosmic-universe" }
cosmic-artifact={ path="../../cosmic/cosmic-artifact"}
lru = "0.7.7"