[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-macros = { path="../cosmic-macros",version = "0.4.0-alpha1"}
cosmic-space = { path= "../cosmic-space",version = "0.4.0-alpha1"}