[package]
name = "cosmic-hyperlane"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true




[dependencies]
cosmic-space = { path= "../cosmic-space",version = "0.3.6"}
async-trait = "0.1.48"
futures = {version = "0.3.21", default-features = true }
tokio = { version = "1.15.0", features = ["full"] }
dashmap = "5.3.4"
semver = { version="1.0.10", features=['serde'] }
lazy_static = "1.4.0"
strum_macros = "0.24.1"
uuid = { version="1.1.2", features=["v4"] }

[dev-dependencies]
chrono = { version="0.4.19", features=["serde"] }
