[package]
name = "starlane"

description = "Starlane -- A Mesh for extending any enterprise resource with WebAssembly!  Starlane is the Reference implementation of the Cosmic Initiative: http://thecosmicinitiative.io (A WebAssembly Orchestration Framework)"


version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
postgres=["dep:cosmic-registry-postgres"]

[dependencies]
cosmic-space={ path= "../../cosmic/cosmic-space" ,version = "0.3.14" }
cosmic-hyperspace={ path= "../../cosmic/cosmic-hyperspace" ,version = "0.3.14" }
cosmic-registry-postgres={ path= "../../cosmic/cosmic-registry-postgres" ,version = "0.3.14", optional=true}
cosmic-hyperlane={ path="../../cosmic/cosmic-hyperlane",version = "0.3.14" }
cosmic-hyperlane-tcp={ path="../../cosmic/cosmic-hyperlane-tcp",version = "0.3.14" }
mechtron-host={ path="../../mechtron/mechtron-host",version = "0.3.14" }
lazy_static = "1.4.0"
uuid = { version="1.1.2", features=["v4"] }
chrono = { version="0.4.19", features=["serde"] }
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.48"
ctrlc = "3.2.2"
bincode = "1.3.3"
sqlx = { version = "0.5.11", features = [ "runtime-tokio-rustls", "postgres", "macros", "any" ] }
strum = "0.24.1"
strum_macros = "0.24.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
acid-store = {git="https://github.com/uberscott/acid-store.git" , version="0.14.2" }



zip = "0.6.2"
dirs = "4.0.0"
ascii = "1.1.0"
url = "2.3.1"

