[package]
name = "starlane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-universe={ path= "../../cosmic/cosmic-universe" }
cosmic-hyperverse={ path= "../../cosmic/cosmic-hyperverse" }
cosmic-registry-postgres={ path= "../../cosmic/cosmic-registry-postgres" }
cosmic-hyperlane={ path="../../cosmic/cosmic-hyperlane"}
cosmic-hyperlane-tcp={ path="../../cosmic/cosmic-hyperlane-tcp"}
mechtron-host={ path="../../mechtron/mechtron-host"}
lazy_static = "1.4.0"
uuid = { version="1.1.2", features=["v4"] }
chrono = { version="0.4.19", features=["serde"] }
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.48"
ctrlc = "3.2.2"
bincode = "1.3.3"
sqlx = { version = "0.5.11", features = [ "runtime-tokio-rustls", "postgres", "macros", "any" ] }
strum = "0.24.1"
strum_macros = "0.24.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
acid-store = { version = "0.12.0", features=['store-directory','repo-value'] }
zip = "0.6.2"

