[package]
name = "starlane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-api={ path="../../cosmic/cosmic-api"}
cosmic-star={ path="../../cosmic/cosmic-star"}
cosmic-registry-postgres={ path="../../drivers/cosmic-registry-postgres"}
cosmic-artifact={ path="../../cosmic/cosmic-artifact"}
lazy_static = "1.4.0"
uuid = { version="1.1.2", features=["v4"] }
chrono = { version="0.4.19", features=["serde"] }
tokio = { version = "1.15.0", features = ["full"] }
