[package]
name = "starlane"

description = "Starlane -- A Mesh for extending any enterprise resource with WebAssembly!  Starlane is the Reference implementation of the Cosmic Initiative: http://thecosmicinitiative.io (A WebAssembly Orchestration Framework)"


version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
full=["server"]
default=["server"]
server=["hyperspace", "postgres"]
hyperspace=["dep:futures","dep:dashmap","dep:semver"]
postgres=[ "dep:sqlx","dep:serde","dep:tracing","dep:async-recursion" ]

[dependencies]
cosmic-space={ path= "../../cosmic/cosmic-space" ,version = "0.3.14" }
cosmic-hyperlane={ path="../../cosmic/cosmic-hyperlane",version = "0.3.14" }
cosmic-hyperlane-tcp={ path="../../cosmic/cosmic-hyperlane-tcp",version = "0.3.14" }
mechtron-host={ path="../../mechtron/mechtron-host",version = "0.3.14" }
lazy_static = {  workspace=true  }
uuid = { workspace=true, features=["v4"] }
chrono = { workspace=true, features=["serde"] }
tokio = { workspace=true, features = ["full"] }
async-trait = {workspace = true}
ctrlc = {workspace = true}
bincode = {workspace = true}
strum =  {workspace = true}
strum_macros = {workspace = true}
wasmer = {workspace = true}
wasmer-compiler-singlepass = {workspace = true}
#acid-store = {git="https://github.com/uberscott/acid-store.git" , version="0.14.2" }



zip = { workspace=true }
dirs ={ workspace=true }
ascii ={ workspace=true }
url ={ workspace=true }

# hyperspace requirements
futures = {workspace=true, default-features = true, optional=true }
dashmap = {workspace=true, optional = true}
semver = { workspace=true, features=['serde'], optional = true }


# postgres deps
sqlx = { workspace = true, features = [ "runtime-tokio-rustls", "postgres", "macros", "any" ], optional = true }
serde = { workspace = true, features=['derive','rc'], optional=true }
tracing = { workspace = true, optional = true}
async-recursion = { workspace = true, optional=true }


[lib]
name = "starlane"
path="src/lib.rs"


[[bin]]
name = "starlane"
doc = false
path = "src/main.rs"