[package]
name = "cosmic-hyperverse"
version = "0.3.0-alpha8"
edition = "2021"

authors = ["Scott Williams <scott@mightydevco.com>"]
description = "The Cosmic Hyperverse is the infrastructure component of The Cosmic Initiative framework that orchestrates and enforces security.  It is responsible for making the universe painless to extend by supplying goodies such as provisioning, sharding, load balancing, routing, discovery & of course security."
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
cosmic-macros = { path="../cosmic-macros"}
cosmic-universe = { path= "../cosmic-universe" ,version = "0.3.0-alpha8"}
cosmic-nom = { path="../cosmic-nom"}
cosmic-hyperlane = { path= "../cosmic-hyperlane" }
anyhow = "1.0.44"
dashmap = "5.3.4"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version="1.0.69", features=['derive','rc'] }
lazy_static = "1.4.0"
async-trait = "0.1.48"
regex = "1.5.4"
http = "0.2.6"
futures = "0.3.21"
ctrlc = "3.2.2"
tracing = "0.1.35"
strum = "0.24.1"
strum_macros = "0.24.1"

chrono = { version="0.4.19", features=["serde"] }
uuid = { version="1.1.2", features=["v4"] }
