[package]
name = "filesystem"
version = "0.1.1"
description = "Package to showcase a news scraper on wasmer edge"
wasmer-extra-flags = "--net --enable-threads --enable-bulk-memory"

[dependencies]

[[module]]
name = "filesystem"
source = "./target/wasm32-wasmer-wasi/debug/filesystem.wasm"

[[command]]
name = "filesystem"
module = "filesystem"
runner = "wasi@unstable_"
