[package]
name = "starlane-core"
version = "0.2.0-rc1"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"
description = "Resource Mesh"
homepage = "http://starlane.io"
repository = "https://github.com/mechtronium/starlane"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
oneshot = "0.1.3"
anyhow = "1.0.44"
dashmap = "4.0.2"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version="1.0.69", features=['derive','rc'] }
serde_yaml = "0.8.19"
#serde_json = "1.0"
serde_json = "1.0.61"
futures = {version = "0.3.21", default-features = false }
threadpool = "1.8.1"
log = "0.4.14"
async-trait = "0.1.48"
url = "2.2.1"
lru = "0.6.5"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
bincode = "1.3.3"
lazy_static = "1.4.0"
semver = "0.11.0"
error-chain = "0.12.4"
validate = "0.6.1"
notify = "4.0.17"
walkdir = "2.3.2"
#actix-web = "3.3.2"
actix-web = "4.0.1"
#actix-http = "2.2.0"
#actix-rt= "1.1.1"
#actix-server= "1.0.0"
tempdir = "0.3.7"
zip = "0.5.13"
nom = "7"
nom-supreme = "0.6.0"
mysql = "20.1.0"
tracing = "0.1.26"
#tracing-core = "0.1.18"
tracing-subscriber = '0.2.19'
tracing-futures = "0.2.5"
strum = "0.21.0"
strum_macros = "0.21.1"
ctrlc = { version="3.1.9", features=["termination"] }
clap = { version="2.33", features=["yaml"] }
yaml-rust = "0.3.5"
tempfile = "3.2.0"
regex = "1.5.4"
chrono = "0.4.19"

kube = { version = "0.57.0", features = ["derive","native-tls"], default-features = false}
kube-runtime = "0.57.0"
kube-derive = { version = "0.57.0", default-features = false } # only needed to opt out of schema
k8s-openapi = { version = "0.12.0", default-features = false, features = ["v1_20"] }
schemars = "0.8.0"
json-patch = "0.2.6"

wasm_membrane_host = { path="../../cosmic/wasm-membrane-host"}
mechtron-common = { path="../../cosmic/mechtron-common"}
wasmer = "2.1.1"
httparse = "1.6.0"
bytes = "1.1.0"
handlebars = "4.1.3"
alcoholic_jwt = "1.0.1"
base64 = "0.13.0"

cosmic-nom={ path="../../cosmic/cosmic-nom"}
cosmic-portal-cli={ path="../../cosmic/cosmic-portal-cli"}
cosmic-macros={ path="../../cosmic/cosmic-macros"}
cosmic-star={ path= "../../cosmic/cosmic-star" }
mesh-portal={ path="../../cosmic/mesh-portal"}
mesh-portal-versions= { path="../../cosmic/mesh-portal-versions"}
mesh-artifact-api ={ path="../../cosmic/mesh-artifact-api", default-features=true }

async-recursion = "1.0.0"

keycloak="13.0.102"
reqwest = "0.11.9"
validator = "0.14.0"
serde_urlencoded = "0.7.1"
http = "0.2.6"
http-serde = "1.1.0"
tiny_http = "0.11.0"
ascii = "1.0.0"
sqlx = { version = "0.5.11", features = [ "runtime-tokio-rustls", "postgres", "macros", "any" ] }