[package]
name = "cosmic-registry-postgres"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

description="various support macros for cosmic"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-space={ path= "../cosmic-space" , version = "0.3.13" }
#cosmic-hyperspace={ path= "../cosmic-hyperspace" }
cosmic-hyperspace={ path= "../cosmic-hyperspace" , version = "0.3.13" }
mechtron-host={ path= "../../mechtron/mechtron-host", version = "0.3.13" }

sqlx = { version = "0.5.11", features = [ "runtime-tokio-rustls", "postgres", "macros", "any" ] }
serde = { version="1.0.69", features=['derive','rc'] }
async-trait = "0.1.48"
tracing = "0.1.26"
async-recursion = "1.0.0"
lazy_static = "1.4.0"
strum = "0.24.1"


[dev-dependencies]
zip = "0.6.2"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
#acid-store = { workspace="true", features=['store-directory','repo-value'] }
bincode = "1.3.3"
tokio = { version = "1.15.0", features = ["full"] }
cosmic-hyperlane= { path="../cosmic-hyperlane" }
ascii = "1.1.0"
url = { version="2.3.1", features=["serde"] }
