[package]
name = "cosmic-nom"
version = "0.3.0-alpha2"
edition = "2021"

authors = ["Scott Williams <scott@mightydevco.com>"]
description = "Cosmic Nom"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT OR Apache-2.0"

[dependencies]
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
serde = { version="1.0.69", features=['derive','rc'] }
