[package]
name = "cosmic-space"
version = "0.3.4"
edition = "2021"

authors = ["Scott Williams <scott@starlane.io>"]
description = "Part of http://thecosmicinitiative.io This package--the Cosmic Space--provides an API and utilities for interacting with the Cosmic Fabric and other Particles within the Spatial Dimension."

homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-nom = { path="../cosmic-nom" ,version = "0.3.4"}
cosmic-macros-primitive = { path="../cosmic-macros-primitive" ,version = "0.3.4"}
ariadne = "0.1.5"
async-trait = "0.1.48"
lazy_static = "1.4.0"
serde = { version="1.0.69", features=['derive','rc'] }
strum = "0.24.1"
strum_macros = "0.24.1"
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
bincode = "1.3.3"
semver = { version="1.0.10", features=['serde'] }
regex = "1.5.4"
#http = "0.2.6"
#http-serde = "1.1.0"
serde_json = "1.0.79"
tokio = { version = "1.15.0", features = ["rt","sync","time"] }
dashmap = "5.3.4"
serde_urlencoded = "0.7.1"
enum-ordinalize = "3.1.11"
convert_case = "0.5.0"
validator = "0.15.0"
url = { version="2.3.1", features=["serde"] }


#uuid = { version="1.1.2", features=["v4", "js"] }
#getrandom = { version = "0.2", features = ["js"] }
#chrono = { version="0.4.19", features=["serde", "js-sys"] }
