[package]
name = "starlane-macros-test"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starlane-macros = { path = "../starlane-macros" }
starlane-core = { path = "../starlane-core" }
serde = { version="1.0.69", features=['derive','rc'] }
nom = "7"
