[package]
name = "cosmic-cli"
version = "0.3.0"
edition = "2021"

authors = ["Scott Williams <scott@mightydevco.com>"]
description = "The Cosmic Cli provides command line inerface access to running cosmos like http://starlane.io"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

[dependencies]
