[workspace.package]

license = "MIT"
repository = "https://github.com/cosmic-initiative/cosmic-initiative.git"

version = "0.3.14"

edition = "2021" 
rust-version = "1.80.1"
authors = []
homepage = "https://starlane.io"
description="..."



[workspace]
resolver = "2"
members = [
  "starlane/*",
  "cosmic/*",
  "mechtron/*",
  ]

exclude = [
  "cosmic/src", "cosmic/target", "starlane/starlane-old", "starlane/starlane-core", "starlane/starlane-macros","mechtron/mocks",  "mechtron/mocks/hello-goodbye", "cosmic/cosmic-hyperlane-quic", "driver"


]

[workspace.dependencies]

acid-store = {git="https://github.com/uberscott/acid-store.git",  features=['store-directory','repo-value'] , version="0.14.2" }


