[workspace]
members = [
  "starlane/*",
  "cosmic/*",
  "mechtron/*",
  "wasm/*",
  ]

exclude = [
  "cosmic/src", "cosmic/target", "starlane/starlane-old", "starlane/starlane-core", "mechtron/mocks"
]

