
[workspace.package]
package = "false"
edition = "2021"
rust-version = "1.80.1"
authors = ["Scott Williams"]
homepage = "https://starlane.io"
license = "MIT"
repository = ""

version = "0.3.7"


[workspace]
members = [
  "starlane/*",
  "cosmic/*",
  "mechtron/*",
  ]

exclude = [
  "cosmic/src", "cosmic/target", "starlane/starlane-old", "starlane/starlane-core", "starlane/starlane-macros","mechtron/mocks",  "mechtron/mocks/hello-goodbye", "cosmic/cosmic-hyperlane-quic"


]

[workspace.dependencies]
acid-store = { git="https://github.com/uberscott/acid-store.git" }




