[workspace]
members = [
  "starlane/*",
  "cosmic/*",
  "mechtron/*",
  ]

exclude = [
  "cosmic/src", "cosmic/target", "starlane/starlane-old", "starlane/starlane-core", "starlane/starlane-macros","mechtron/mocks" , "cosmic/cosmic-hyperlane-quic"
]

