[workspace]
members = [
  "starlane/*",
  "cosmic/*",
  "mechtron/*",
  ]

exclude = [
  "cosmic/src", "cosmic/target", "starlane/starlane-old", "starlane/starlane-core", "starlane/starlane-macros","mechtron/mocks",  "mechtron/mocks/hello-goodbye", "cosmic/cosmic-hyperlane-quic"


]

