[package]
name = "wasm_membrane_guest"
version = "0.2.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"
license = "MIT"
homepage ="http://starlane.io/"
repository = "https://github.com/mechtronium/starlane"
description = "Host environment to facilitate communication with Wasm"


[dependencies]
lazy_static = {version="1.4.0", features=["spin_no_std"] }
tokio = { version="1.21.1", features=["rt","sync"] }
dashmap = "5.3.4"

