[package]
name = "mechtron"
version = "0.3.3"
authors = ["Scott Williams <scott@starlane.io>"]
edition = "2021"
description = "Part of http://thecosmicinitiative.io This package--MECHTRON--provides an API and framework that allows a Wasm component to send and receive messages from other Wasm components."

homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"



#[lib]
#crate-type = ["cdylib", "rlib"]


[dependencies]
lazy_static = {version="1.4.0", features=["spin_no_std"] }
bincode = "1.3.3"
cosmic-space= { path= "../../cosmic/cosmic-space" ,version = "0.3.3"}
cosmic-macros= { path= "../../cosmic/cosmic-macros" ,version = "0.3.3"}
serde = { version="1.0.69", features=['derive','rc'] }
dashmap = "5.3.4"
cosmic-macros-primitive = {path="../../cosmic/cosmic-macros-primitive" }
# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
[profile.release]
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
