[package]
name = "cosmic-hyperlane-tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.48"
cosmic-hyperlane= { path= "../cosmic-hyperlane" }
cosmic-universe = { path= "../cosmic-universe" }
tokio-openssl = "0.6.3"
tokio = { version = "1.20.1", features = ["full"] }
rcgen = "0.9.3"
openssl = "0.10.41"
semver = { version="1.0.10", features=['serde'] }
bincode = "1.3.3"
