[package]
name = "cosmic-hyperlane-tcp"
version = "0.3.3"
edition = "2021"

authors = ["Scott Williams <scott@starlane.io>"]
description = "Adds TCP server and client to cosmic-hyperlane"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

[dependencies]
async-trait = "0.1.58"
cosmic-hyperlane= { path= "../cosmic-hyperlane" ,version = "0.3.3"}
cosmic-space = { path= "../cosmic-space",version = "0.3.3"}
# tokio-openssl = "0.6.3"
tokio-rustls = "0.23"
tokio = { version = "1.21.2", features = ["full"] }
rcgen = "0.10.0"
# openssl = "0.10.41"
rustls = "0.20"
semver = { version="1.0.14", features=['serde'] }
bincode = "1.3.3"
tls-api-rustls = "0.9.0"

[dev-dependencies]
uuid = { version="1.2.1", features=["v4"] }
chrono = { version="0.4.22", features=["serde"] }
