[package]
name = "cosmic-hyperlane-tcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

description = "Adds TCP server and client to cosmic-hyperlane"

[dependencies]
async-trait = "0.1.48"
cosmic-hyperlane= { path= "../cosmic-hyperlane" , version = "0.3.12" }
cosmic-space = { path= "../cosmic-space", version = "0.3.12" }
tokio-rustls = "0.23"
tokio = { version = "1.20.1", features = ["full"] }
rcgen = "0.9.3"
rustls = "0.20"
semver = { version="1.0.10", features=['serde'] }
bincode = "1.3.3"
tls-api-rustls = "0.9.0"

[dev-dependencies]
uuid = { version="1.1.2", features=["v4"] }
chrono = { version="0.4.19", features=["serde"] }
