[package]
name = "cosmic-hyperlane-tcp"
version = "0.3.0"
edition = "2021"

authors = ["Scott Williams <scott@mightydevco.com>"]
description = "Adds TCP server and client to cosmic-hyperlane"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"

[dependencies]
async-trait = "0.1.48"
cosmic-hyperlane= { path= "../cosmic-hyperlane" ,version = "0.3.0"}
cosmic-universe = { path= "../cosmic-universe" ,version = "0.3.0"}
tokio-openssl = "0.6.3"
tokio = { version = "1.20.1", features = ["full"] }
rcgen = "0.9.3"
openssl = "0.10.41"
semver = { version="1.0.10", features=['serde'] }
bincode = "1.3.3"

[dev-dependencies]
uuid = { version="1.1.2", features=["v4"] }
chrono = { version="0.4.19", features=["serde"] }