# permissions for end users to view postgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-viewer-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - postgres/status
  verbs:
  - get
