[package]
name = "cosmic-macros-primitive"
version = "0.3.3"
edition = "2021"

authors = ["Scott Williams <scott@starlane.io>"]
description = "Some primitive macros needed to jump start cosmic-space"
homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"


[lib]
proc-macro = true
doctest = false

[dependencies]

syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
