[package]
name = "cosmic-macros-primitive"
description = "Some primitive macros needed to jump start cosmic-space"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true




[lib]
proc-macro = true
doctest = false

[dependencies]

syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
