[package]
name = "mechtron-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm_membrane_host = { path= "../wasm-membrane-host" ,version = "0.3.0"}
cosmic-universe = { path="../cosmic-universe"}
threadpool = "1.8.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"



