[package]
name = "mechtron-host"
version = "0.3.6-rc1"

authors = ["Scott Williams <scott@starlane.io>"]
edition = "2021"
description = "Part of http://thecosmicinitiative.io This package--MECHTRON HOST--provides a wasm runtime"

homepage = "http://thecosmicinitiative.io"
repository = "https://github.com/cosmic-initiative/cosmic-initiative"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-space = { path= "../../cosmic/cosmic-space" ,version = "0.3.6-rc1"}
threadpool = "1.8.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
bincode = "1.3.3"
chrono = { version="0.4.19", features=["serde"] }
uuid = { version="1.1.2", features=["v4"] }
oneshot = "0.1.5"
tokio = { version = "1.15.0", features = ["full"] }
lazy_static = {version="1.4.0"}
