[package]
name = "mechtron-host"
description = "Part of http://thecosmicinitiative.io This package--MECHTRON HOST--provides a wasm runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-space = { path= "../../cosmic/cosmic-space" ,version = "0.3.12" }
threadpool = "1.8.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
bincode = "1.3.3"
chrono = { version="0.4.19", features=["serde"] }
uuid = { version="1.1.2", features=["v4"] }
oneshot = "0.1.5"
tokio = { version = "1.15.0", features = ["full"] }
lazy_static = {version="1.4.0"}
