[package]
name = "mechtron-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#wasm_membrane_host = { path= "../wasm-membrane-host" ,version = "0.3.0"}
cosmic-space = { path= "../../cosmic/cosmic-space" }
threadpool = "1.8.1"
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"

bincode = "1.3.3"
chrono = { version="0.4.19", features=["serde"] }
uuid = { version="1.1.2", features=["v4"] }

