[package]
name = "driver-host"
license = "MIT"
repository = "https://github.com/cosmic-initiative/cosmic-initiative.git"

version = "0.3.14"

edition = "2021" 
rust-version.workspace = true
authors = []
homepage = "https://starlane.io"
description="..."




[dependencies]
wasmer= {  path = "../api" }
wasmer-wasix = {  path = "../wasix", features=["sys-thread"] }

tokio = { version="1.40.0", features=["full"] }
anyhow = "1.0.86"
virtual-fs = { path= "../virtual-fs" }
futures = { version = "0.3" }
futures-core = "0.3.30"
