[package]
name = "cosmic-platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-macros = { path="../cosmic-macros"}
cosmic-api = { path= "../cosmic-api" }
cosmic-nom = { path="../cosmic-nom"}
cosmic-hyperlane = { path= "../cosmic-hyperlane" }
cosmic-driver = { path= "../cosmic-driver" }
anyhow = "1.0.44"
dashmap = "5.3.4"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version="1.0.69", features=['derive','rc'] }
lazy_static = "1.4.0"
async-trait = "0.1.48"
regex = "1.5.4"
http = "0.2.6"
futures = "0.3.21"
ctrlc = "3.2.2"
tracing = "0.1.35"