[package]
name = "hyperlane-quic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-hyperlane= { path= "../cosmic-hyperlane" }
cosmic-universe = { path= "../cosmic-universe" }
dashmap = "5.3.4"
quinn = "0.8.5"
rustls = { version = "0.20.6", features = ["dangerous_configuration", "quic"] }
semver = { version="1.0.10", features=['serde'] }
tokio = { version = "1.15.0", features = ["full"] }
rcgen = "0.9.2"