[package]
name = "hyperlane-quic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "legacy based on quic"

[dependencies]
cosmic-hyperlane= { path= "../cosmic-hyperlane" }
cosmic-space = { path= "../cosmic-space" }
dashmap = "5.3.4"
quinn = "0.8.5"
rustls = { version = "0.20.6", features = ["dangerous_configuration", "quic"] }
semver = { version="1.0.10", features=['serde'] }
tokio = { version = "1.15.0", features = ["full"] }
rcgen = "0.9.2"
