[package]
name = "mechtron-test"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
mechtron= { path="../../cosmic/mechtron" }
wasm_membrane_guest = { path= "../../cosmic/wasm-membrane-guest"}
cosmic-universe= { path= "../../cosmic/cosmic-universe"}
tokio = { version = "1.15.0", features = ["rt","sync"] }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
#wee_alloc = { version = "0.4.5", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
#lto = true
#codegen-units = 1
#panic = "abort"
